In [2]:
import numpy as np
import pandas as pd

In [3]:
left2 = pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                    index = ['a','c','e'],
                    columns=['Ohio','Nevada'])

In [4]:
right2 = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                     index=['b','c','d','e'],
                     columns = ['Missouri','Albama'])

In [5]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [6]:
right2

Missouri  Albama
b       7.0     8.0
c       9.0    10.0
d      11.0    12.0
e      13.0    14.0

In [7]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

Ohio  Nevada  Missouri  Albama
a   1.0     2.0       NaN     NaN
b   NaN     NaN       7.0     8.0
c   3.0     4.0       9.0    10.0
d   NaN     NaN      11.0    12.0
e   5.0     6.0      13.0    14.0

In [9]:
left2.join(right2,how='outer')

Ohio  Nevada  Missouri  Albama
a   1.0     2.0       NaN     NaN
b   NaN     NaN       7.0     8.0
c   3.0     4.0       9.0    10.0
d   NaN     NaN      11.0    12.0
e   5.0     6.0      13.0    14.0

In [10]:
another = pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[16.,17.]],
                      index = ['a','c','e','f'],
                      columns = ['New York','Oregeon'])

In [11]:
another

New York  Oregeon
a       7.0      8.0
c       9.0     10.0
e      11.0     12.0
f      16.0     17.0

In [12]:
left2.join([right2,another])

Ohio  Nevada  Missouri  Albama  New York  Oregeon
a   1.0     2.0       NaN     NaN       7.0      8.0
c   3.0     4.0       9.0    10.0       9.0     10.0
e   5.0     6.0      13.0    14.0      11.0     12.0

In [13]:
left2.join([right2,another],how='outer')

Ohio  Nevada  Missouri  Albama  New York  Oregeon
a   1.0     2.0       NaN     NaN       7.0      8.0
c   3.0     4.0       9.0    10.0       9.0     10.0
e   5.0     6.0      13.0    14.0      11.0     12.0
b   NaN     NaN       7.0     8.0       NaN      NaN
d   NaN     NaN      11.0    12.0       NaN      NaN
f   NaN     NaN       NaN     NaN      16.0     17.0

> Concatenating Along an Axis

In [15]:
arr = np.arange(12).reshape((3,4))

In [16]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [18]:
s1 = pd.Series([0,1],index=['a','b'])

In [19]:
s2 = pd.Series([2,3,4],index=['c','d','e'])

In [20]:
s3 = pd.Series([5,6],index=['f','g'])

In [21]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [22]:
pd.concat([s1,s2,s3],axis=1)

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [23]:
s4 = pd.concat([s1,s3])

In [24]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [25]:
pd.concat([s1,s4],axis=1)

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [26]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  1

In [27]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [28]:
result = pd.concat([s1,s2,s3],keys=['one','two','three'])

In [29]:
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [30]:
result.unstack()

a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [31]:
pd.concat([s1,s2,s3],axis=1,keys=['one','two','three'])

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [32]:
df1 = pd.DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],
                  columns=['one','two'])

In [33]:
df2 = pd.DataFrame(np.arange(4).reshape(2,2),index=['a','c'],
                  columns=['three','four'])

In [34]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [35]:
df2

three  four
a      0     1
c      2     3

In [36]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'])

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0

In [37]:
pd.concat({'level1':df1,'level2':df2},axis=1)

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


level1     level2     
     one two  three four
a      0   1    0.0  1.0
b      2   3    NaN  NaN
c      4   5    2.0  3.0

In [38]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],
         names=['upper','lower'])

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


upper level1     level2     
lower    one two  three four
a          0   1    0.0  1.0
b          2   3    NaN  NaN
c          4   5    2.0  3.0

In [39]:
pd.concat([df1,df2],axis=1,keys=['level1','level2'],
         names=['upper','lower'])

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


upper level1     level2     
lower    one two  three four
a          0   1    0.0  1.0
b          2   3    NaN  NaN
c          4   5    2.0  3.0

In [40]:
df1 = pd.DataFrame(np.random.randn(3,4),columns = ['a','b','c','d'])

In [41]:
df2 = pd.DataFrame(np.random.randn(2,3),columns= ['b','d','a'])

In [42]:
df1

a         b         c         d
0  0.147915 -0.833212 -0.116864  0.261492
1  1.053883 -0.722725 -0.228900  0.535466
2 -0.933746  1.438783 -1.043540  1.229494

In [43]:
df2

b         d         a
0 -2.179772 -1.615802  0.688752
1 -1.991276 -0.545646  0.187609

In [44]:
pd.concat([df1,df2],ignore_index=True)

c:\users\chitr\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


a         b         c         d
0  0.147915 -0.833212 -0.116864  0.261492
1  1.053883 -0.722725 -0.228900  0.535466
2 -0.933746  1.438783 -1.043540  1.229494
3  0.688752 -2.179772       NaN -1.615802
4  0.187609 -1.991276       NaN -0.545646

> Combining Data with Overlap

In [47]:
a = pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
             index=['f','e','d','c','b','a'])

In [48]:
b = pd.Series([0.0,np.nan,2,np.nan,np.nan,5.],
             index=['a','b','c','d','e','f'])

In [49]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [50]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [51]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [52]:
b.combine_first(a)

a    0.0
b    4.5
c    2.0
d    0.0
e    2.5
f    5.0
dtype: float64

In [54]:
df1 = pd.DataFrame({
    'a': [1.,np.nan,5.,np.nan],
    'b' : [np.nan,2.,np.nan,6.],
    'c' : range(2,18,4)
})

In [55]:
df2 = pd.DataFrame({'a':[5.,4.,np.nan,3.,7.],
                   'b':[np.nan,3.,4.,6.,8.]})

In [56]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [57]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [58]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# Reshaping and Pivoting 

> **Stack** : This rotates or pivots from the columns in the data to the rows. **Unstack** :Rows into columns

In [60]:
data = pd.DataFrame(np.arange(6).reshape((2,3)),
                   index=pd.Index(['Ohio','Colorado'],name='state'),
                   columns = pd.Index(['one','two','three'],
                                     name='number'))

In [61]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [62]:
result = data.stack()

In [63]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [64]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [65]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [66]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [67]:
s1 = pd.Series([0,1,2,3],index = ['a','b','c','d'])

In [68]:
s2 = pd.Series([4,5,6],index=['c','d','e'])

In [69]:
data2 = pd.concat([s1,s2],keys=['one','two'])

In [70]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [71]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [72]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [73]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [74]:
df = pd.DataFrame({'left':result,'right':result+5},
                 columns=pd.Index(['left','right'],name='side'))

In [75]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [77]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [78]:
df.unstack('state').stack('side')

state         Colorado  Ohio
number side                 
one    left          3     0
       right         8     5
two    left          4     1
       right         9     6
three  left          5     2
       right        10     7