**Series**

> 1-D array of similar datatypes

In [1]:
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])

In [6]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj2['a']

-5

In [10]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [11]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [12]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [13]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

> Another way to think about a Series is as a fixed-length,ordered dict,as it is a map-ping of index values to data values.It can be used in many contexts where we might use a dict

In [14]:
'b' in obj2

True

In [15]:
'e' in obj2

False

In [16]:
sdata = {'Ohio':35000,'Texas':71000,'Oregeon':16000,'Utah':5000}

In [17]:
obj3 = pd.Series(sdata)

In [18]:
obj3

Ohio       35000
Texas      71000
Oregeon    16000
Utah        5000
dtype: int64

In [19]:
states = ['California','Ohio','Oregeon','Texas']

In [20]:
obj4 = pd.Series(sdata,index=states)

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregeon       16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregeon       False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregeon        True
Texas          True
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregeon       False
Texas         False
dtype: bool

In [25]:
obj3

Ohio       35000
Texas      71000
Oregeon    16000
Utah        5000
dtype: int64

In [26]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregeon        32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'population'

In [28]:
obj4.index.name = 'states'

In [29]:
obj4

states
California        NaN
Ohio          35000.0
Oregeon       16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj4.index

Index(['California', 'Ohio', 'Oregeon', 'Texas'], dtype='object', name='states')

# Dataframe

> A dataframe represents a rectangular table of data and contains an ordered collection of columns ,each of which can be a different data type

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}

In [32]:
frame = pd.DataFrame(data)

In [33]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [34]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [35]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [36]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])

In [37]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [40]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
frame2['debt'] = np.arange(6.)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [47]:
frame2['debt'] = val

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
frame2['eastern'] =frame2.state == 'Ohio'

In [50]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [51]:
del frame2['eastern']

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [54]:
frame3 = pd.DataFrame(pop)

In [55]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [56]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [57]:
pd.DataFrame(pop,index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}

In [59]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [60]:
frame3.index.name = 'year';
frame3.columns.name = 'state'

In [61]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [62]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [63]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

**Index Objects**

In [64]:
obj = pd.Series(range(3),index=['a','b','c'])

In [65]:
index = obj.index

In [66]:
index

Index(['a', 'b', 'c'], dtype='object')

In [67]:
index[1:]

Index(['b', 'c'], dtype='object')

In [68]:
index[1] = 'd' 

TypeError: Index does not support mutable operations

In [69]:
labels = pd.Index(np.arange(3))

In [70]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [71]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [72]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [73]:
obj2.index is labels

True

In [74]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [75]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [76]:
'Ohio' in frame3.columns

True

In [77]:
2003 in frame3.index

False

In [78]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [79]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Essential Functionality

**Reindexing**

In [80]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [81]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [82]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [83]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [84]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [85]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [86]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [87]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],
                    columns = ['Ohio','Texas','California'])

In [88]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [89]:
frame2 = frame.reindex(['a','b','c','d'])

In [90]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [91]:
states = ['Texas','Utah','California']

In [92]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [93]:
frame.loc[['a','b','c','d'],states]

C:\Users\chitr\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [94]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [95]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [96]:
new_obj = obj.drop('c')

In [97]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [98]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [99]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [103]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [104]:
obj.drop('c',inplace=True)

In [105]:
obj[1]

1.0

In [106]:
obj[2:4]

d    3.0
e    4.0
dtype: float64

In [107]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [108]:
obj[[1,3]]

b    1.0
e    4.0
dtype: float64

In [109]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [110]:
obj['b':'c']

b    1.0
dtype: float64

In [111]:
obj['b':'c'] = 5

In [112]:
obj

a    0.0
b    5.0
d    3.0
e    4.0
dtype: float64

In [114]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],
                    columns = ['one','two','three','four'])

In [115]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [117]:
data[['three','four']]

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [118]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [119]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [121]:
data[data<5]=0

In [123]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

> Selection with loc and iloc

In [124]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [125]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [126]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [127]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [128]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [129]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

> Integer Indexes

In [130]:
ser = pd.Series(np.arange(3.))

In [131]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [133]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [134]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [135]:
ser2[-1]

2.0

In [136]:
ser[-1]

KeyError: -1

In [137]:
ser.iloc[-1]

2.0

In [138]:
ser[:2]

0    0.0
1    1.0
dtype: float64

> Arithmetic and Data Alignment

In [139]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],
              index=['a','b','c','d'])

In [140]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index=['a','c','e','f','g'])

In [141]:
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [142]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [143]:
s1+s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [144]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns = list('bcd'),
                  index = ['Ohio','Texas','Colorado'])

In [145]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns = list('bde'),
                  index = ['Utah','Ohio','Texas','Oregeon'])

In [146]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [147]:
df2

b     d     e
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Oregeon  9.0  10.0  11.0

In [148]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregeon   NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [149]:
df1 = pd.DataFrame({'A':[1,2]})

In [150]:
df2 = pd.DataFrame({'B':[3,4]})

In [151]:
df1

A
0  1
1  2

In [152]:
df2

B
0  3
1  4

In [153]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

> Arithmetic methods with fill values

In [156]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns = list('abcd'))

In [157]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns = list('abcde'))

In [158]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [159]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [160]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [161]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [162]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [163]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [164]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

> Operations between DataFrame and Series

In [165]:
arr = np.arange(12.).reshape((3,4))

In [166]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [167]:
arr[0]

array([0., 1., 2., 3.])

In [168]:
arr - arr[0] #Broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [169]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregeon'])

In [170]:
frame

b     d     e
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Oregeon  9.0  10.0  11.0

In [171]:
series = frame.iloc[0]

In [172]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [173]:
frame - series

b    d    e
Utah     0.0  0.0  0.0
Ohio     3.0  3.0  3.0
Texas    6.0  6.0  6.0
Oregeon  9.0  9.0  9.0

In [174]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [175]:
frame + series2

b   d     e   f
Utah     0.0 NaN   3.0 NaN
Ohio     3.0 NaN   6.0 NaN
Texas    6.0 NaN   9.0 NaN
Oregeon  9.0 NaN  12.0 NaN

In [176]:
series3= frame['d']

In [177]:
frame

b     d     e
Utah     0.0   1.0   2.0
Ohio     3.0   4.0   5.0
Texas    6.0   7.0   8.0
Oregeon  9.0  10.0  11.0

In [178]:
series3

Utah        1.0
Ohio        4.0
Texas       7.0
Oregeon    10.0
Name: d, dtype: float64

In [180]:
frame.sub(series3,axis='index') #axis = 'index' or axis=0

b    d    e
Utah    -1.0  0.0  1.0
Ohio    -1.0  0.0  1.0
Texas   -1.0  0.0  1.0
Oregeon -1.0  0.0  1.0

> Function Application and Mapping


Element wise array methods

In [181]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                     index=['Utah','Ohio','Texas','Oregeon'])

In [182]:
frame

b         d         e
Utah     0.242987  0.566838 -0.113766
Ohio     0.582479 -0.233299  1.116863
Texas   -0.406612  1.377378 -0.433235
Oregeon -0.533926 -0.559391  1.240033

In [183]:
np.abs(frame)

b         d         e
Utah     0.242987  0.566838  0.113766
Ohio     0.582479  0.233299  1.116863
Texas    0.406612  1.377378  0.433235
Oregeon  0.533926  0.559391  1.240033

In [184]:
f = lambda x :x.max() - x.min()

In [186]:
frame.apply(f)

b    1.116405
d    1.936769
e    1.673268
dtype: float64

In [187]:
frame.apply(f,axis='columns')

Utah       0.680604
Ohio       1.350162
Texas      1.810612
Oregeon    1.799425
dtype: float64

In [188]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [189]:
frame.apply(f)

b         d         e
min -0.533926 -0.559391 -0.433235
max  0.582479  1.377378  1.240033

In [190]:
format = lambda x :'%.2f' % x

In [192]:
frame.applymap(format) #we want to apply the function with floating value with applymap

b      d      e
Utah      0.24   0.57  -0.11
Ohio      0.58  -0.23   1.12
Texas    -0.41   1.38  -0.43
Oregeon  -0.53  -0.56   1.24

In [193]:
frame['e'].map(format) #Series has a map method for applying an element wise function

Utah       -0.11
Ohio        1.12
Texas      -0.43
Oregeon     1.24
Name: e, dtype: object

> Sorting and Ranking

In [194]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [195]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [196]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [197]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [198]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [199]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [200]:
obj = pd.Series([4,7,-3,2])

In [201]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [203]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [204]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [205]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [206]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [207]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [208]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [209]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [210]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [211]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [212]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [213]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],
                     'a':[0,1,0,1],
                     'c':[-2,5,8,-2.5]})

In [214]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [215]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

> Axis Indexes with Duplicate Labels

In [216]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])

In [217]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [218]:
obj.index.is_unique

False

In [219]:
obj['a']

a    0
a    1
dtype: int64

In [220]:
obj['c']

4

In [221]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [222]:
df

0         1         2
a -0.996744 -0.645566 -0.768044
a  0.217937 -0.195859 -1.082978
b -0.846223 -0.886426  1.874751
b  2.434803  0.265099 -0.002377

In [223]:
df.loc['b']

0         1         2
b -0.846223 -0.886426  1.874751
b  2.434803  0.265099 -0.002377

# Summarizing and Computing Descriptive Statistics

In [225]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                  [np.nan,np.nan],[0.75,-1.3]],
                  index=['a','b','c','d'],
                  columns=['one','two'])

In [226]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [227]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [228]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [229]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [231]:
df.idxmax()

one    b
two    d
dtype: object

In [232]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [233]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [235]:
obj = pd.Series(['a','a','b','c']*4)

In [236]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

> Unique Values,Value Counts, and Membership

In [237]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [238]:
uniques = obj.unique()

In [239]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [240]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [241]:
pd.value_counts(obj.values,sort=False)

d    1
c    3
b    2
a    3
dtype: int64

In [242]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [243]:
mask = obj.isin(['b','c'])

In [244]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [245]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [246]:
unique_vals = pd.Series(['c','b','a'])

In [247]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int32)

In [248]:
data = pd.DataFrame({'Qu1' : [1,3,4,3,4],
                     'Qu2' : [2,3,1,2,3],
                     'Qu3' : [1,5,2,4,4]
})

In [249]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [250]:
result = data.apply(pd.value_counts).fillna(0)

In [251]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0